kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-persistent-storage
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo01"
    type: DirectoryOrCreate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-claim
  labels:
    app: mongopv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongocontainer
  labels:
    appdb: mongocontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: mongodb
  template:
    metadata:
      labels:
        appdb: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.20-xenial
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: hostvol
              mountPath: /data/db
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            claimName: mongo-persistent-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb
  name: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    name: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gerenciadordelogin_springboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: gerenciadordelogin_springboot
    spec:
      containers:
      - name: gerenciadordelogin_springboot
        image: saadapplestore/gerenciador-login-usuario
        env:
    - name: MONGODB_HOST
      value: mongodb
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: gerenciadordelogin_springboot