version: "2.0"
services:
  springboot:
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/gerenciador-login
    container_name: spring-docker
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo
    container_name: mongo-docker
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge